#!/bin/sh

# rofi theme
theme="$HOME/.config/rofi/main_without_icons.rasi"

get_options() {
  echo " Lock"
  echo " Suspend"
  echo " Poweroff"
  echo " Reboot"
  echo " Hibernate"
  echo " Log out"
}

main() {

  # get choice from rofi
  choice=$( (get_options) | rofi -dmenu -i -fuzzy -p "" -theme "$theme")

  # run the selected command
  case $choice in
  ' Lock')
    betterlockscreen -l
    ;;
  ' Suspend')
    /srv/suspend-and-lock.sh
    ;;
  ' Poweroff')
    systemctl poweroff
    ;;
  ' Reboot')
    systemctl reboot
    ;;
  ' Hibernate')
    systemctl hibernate
    ;;
  ' Log out')
    i3-msg exit
    ;;
  esac

  # done
  set -e
}

main &

exit 0
